// protoc --go_out=. -I . -I .. --go_opt=paths=source_relative prototest.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: prototest.proto

package logjson

import (
	_ "github.com/ethanvc/evo/logjson/logjsonproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTest) Reset() {
	*x = ProtoTest{}
	mi := &file_prototest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTest) ProtoMessage() {}

func (x *ProtoTest) ProtoReflect() protoreflect.Message {
	mi := &file_prototest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTest.ProtoReflect.Descriptor instead.
func (*ProtoTest) Descriptor() ([]byte, []int) {
	return file_prototest_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoTest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_prototest_proto protoreflect.FileDescriptor

const file_prototest_proto_rawDesc = "" +
	"\n" +
	"\x0fprototest.proto\x1a\"logjson/logjsonproto/logjson.proto\",\n" +
	"\tProtoTest\x12\x1f\n" +
	"\x06secret\x18\x01 \x01(\tB\a\x8a\x9a0\x03md5R\x06secretB(Z&github.com/ethanvc/evo/logjson;logjsonb\x06proto3"

var (
	file_prototest_proto_rawDescOnce sync.Once
	file_prototest_proto_rawDescData []byte
)

func file_prototest_proto_rawDescGZIP() []byte {
	file_prototest_proto_rawDescOnce.Do(func() {
		file_prototest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prototest_proto_rawDesc), len(file_prototest_proto_rawDesc)))
	})
	return file_prototest_proto_rawDescData
}

var file_prototest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_prototest_proto_goTypes = []any{
	(*ProtoTest)(nil), // 0: ProtoTest
}
var file_prototest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prototest_proto_init() }
func file_prototest_proto_init() {
	if File_prototest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prototest_proto_rawDesc), len(file_prototest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prototest_proto_goTypes,
		DependencyIndexes: file_prototest_proto_depIdxs,
		MessageInfos:      file_prototest_proto_msgTypes,
	}.Build()
	File_prototest_proto = out.File
	file_prototest_proto_goTypes = nil
	file_prototest_proto_depIdxs = nil
}
