// go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// protoc --go_out=. -I . --go_opt=paths=source_relative logjson.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: logjson.proto

package logjsonproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_logjson_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         98721,
		Name:          "logjson",
		Tag:           "bytes,98721,opt,name=logjson",
		Filename:      "logjson.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string logjson = 98721;
	E_Logjson = &file_logjson_proto_extTypes[0]
)

var File_logjson_proto protoreflect.FileDescriptor

const file_logjson_proto_rawDesc = "" +
	"\n" +
	"\rlogjson.proto\x1a google/protobuf/descriptor.proto:<\n" +
	"\alogjson\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x83\x06 \x01(\tR\alogjson\x88\x01\x01B:Z8github.com/ethanvc/evo/logjson/logjsonproto;logjsonprotob\x06proto3"

var file_logjson_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_logjson_proto_depIdxs = []int32{
	0, // 0: logjson:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logjson_proto_init() }
func file_logjson_proto_init() {
	if File_logjson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logjson_proto_rawDesc), len(file_logjson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_logjson_proto_goTypes,
		DependencyIndexes: file_logjson_proto_depIdxs,
		ExtensionInfos:    file_logjson_proto_extTypes,
	}.Build()
	File_logjson_proto = out.File
	file_logjson_proto_goTypes = nil
	file_logjson_proto_depIdxs = nil
}
